# Generated by Django 4.2.6 on 2023-11-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runnerandsponsor',
            old_name='uiid',
            new_name='uuid',
        ),
    ]
