# Generated by Django 4.2.6 on 2023-11-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_alter_marathonresult_common_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathonresult',
            name='charitable_organization',
        ),
        migrations.AddField(
            model_name='runnerandsponsor',
            name='charitable_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='marathon.charitableorganization'),
        ),
    ]
